apiVersion: v1
kind: Service
metadata:
  name: kc-service
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      name: keycloak
      port: 8080
      targetPort: 8080
  type: LoadBalancer
