version: '3.8'

services:
  postgres-db:
    container_name: learn-hub-db
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn_hub_db
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5444
    ports:
      - "5444:5444"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - learn-hub-net

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - learn-hub-net

volumes:
  postgres-data:
    driver: local
networks:
  learn-hub-net:
    driver: bridge