apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-config
data:
  ACTIVE_PROFILE: "prod"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://192.168.0.102:8080/realms/learning-hub-app"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://192.168.0.102:8080/realms/learning-hub-app/protocol/openid-connect/certs"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/eureka/"
  EUREKA_CLIENT_FETCH-REGISTRY: "true"
  EUREKA_CLIENT_REGISTER-WITH-EUREKA: "true"
  EUREKA_INSTANCE_PREFER-IP-ADDRESS: "true"