apiVersion: v1
kind: Service
metadata:
  name: gw-service
spec:
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      name: gw-service
      port: 8222
      targetPort: 8222
  type: LoadBalancer
