spring:
  servlet:
    multipart:
      max-file-size: 100MB
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/learn_hub_db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

tesla:
  oauth2:
    url: http://localhost:9666
    username: admin
    password: admin
    claim:
      id: learning-hub-app

eureka:
  client:
    service-url:
      default-zone: https://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss}) %blue(%level) %red([%thread]) %yellow(%logger{36})-%msg%n"

# metrics
management:
  metrics.distribution.percentiles-histogram.http.server.requests: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus

springdoc:
  default-produces-media-type: application/json

app:
  allowed-origins: http://localhost:4200,http://127.0.0.1:4200

file:
  upload:
    directory: "C:/storage/learn-hub/courses/images"
    db: true