spring:
  servlet:
    multipart:
      max-file-size: 100MB
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/learn_hub_db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  mail:
    host: localhost
    port: 1025
    username: ahmedbaz
    password: ahmedbaz
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          truest: "*"
        auth: true
        starttls.enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

logging:
  level:
    org.springframework: error
  file:
    name: learn-hub-service.log

management:
  endpoints:
    web:
      exposure:
        include: logfile

springdoc:
  default-produces-media-type: application/json


server:
  servlet:
    context-path: /learn-hub/

# security config
secret:
  key: Ij/qOC/GFb1pqPqBweQmYGstENBzLMDxIjlqUeM1+gQr9sB/yqKeq8iRQ0LMrhJYLHpUNPRrQJ43RdGv27Ra1Q==
token:
  expiration:
    access: 10800
    refresh: 259200
