spring:
  servlet:
    multipart:
      max-file-size: 100MB
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-ahmedbaz.k.aivencloud.com:16958/learn_hub_db
    username: avnadmin
    password:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

tesla:
  oauth2:
    url: http://3.252.146.171:9696
    username: admin
    password: admin
    claim:
      id: learning-hub-app

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss}) %blue(%level) %red([%thread]) %yellow(%logger{36})-%msg%n"

# metrics
management:
  metrics.distribution.percentiles-histogram.http.server.requests: true
  zipkin:
    tracing:
      endpoint: http://3.252.146.171:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus

springdoc:
  default-produces-media-type: application/json

app:
  allowed-origins: http://localhost:4200,http://127.0.0.1:4200

file:
  upload:
    directory: "C:/storage/learn-hub/courses/images"
    db: true