version: '3.8'

services:

  learn-hub-service:
    container_name: learn-hub-service
    image: ahmedbaz/learning-hub:3.0.0
    environment:
      ACTIVE_PROFILE: "prod"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-ahmedbaz.k.aivencloud.com:16958/learn_hub_db"
      SPRING_DATASOURCE_USERNAME: "avnadmin"
      SPRING_DATASOURCE_PASSWORD: "AVNS__El0R5G2tDaHErpFOiI"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/eureka/"
      EUREKA_CLIENT_FETCH-REGISTRY: "true"
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "true"
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: "true"
    ports:
      - '8181:9999'
    depends_on:
      - eureka
      - gateway-server
    networks:
      - learn-hub-net

  gateway-server:
    container_name: gateway
    image: ahmedbaz/gateway-server:1.0
    depends_on:
      - eureka
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://192.168.0.102:8080/realms/learning-hub-app"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://192.168.0.102:8080/realms/learning-hub-app/protocol/openid-connect/certs"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/eureka/"
      EUREKA_CLIENT_FETCH-REGISTRY: "true"
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "true"
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: "true"
    ports:
      - '8222:8222'
    networks:
      - learn-hub-net

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.23
    ports:
      - '9411:9411'
    networks:
      - learn-hub-net

  eureka:
    container_name: eureka
    image: ahmedbaz/eureka-server:1.2.0
    environment:
      EUREKA_CLIENT_FETCH-REGISTRY: "false"
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "false"
    ports:
      - '8761:8761'
    networks:
      - learn-hub-net

networks:
  learn-hub-net:
    driver: bridge