apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka-server
          image: ahmedbaz/eureka-server:1.2.0
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: eureka-config