apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-hub-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learn-hub-app
  template:
    metadata:
      labels:
        app: learn-hub-app
    spec:
      containers:
        - name: learn-hub-service
          image: ahmedbaz/learning-hub:2.0.1
          ports:
            - containerPort: 9999
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: be-secret
                  key: db_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: be-secret
                  key: db_password
          envFrom:
            - configMapRef:
                name: be-config