apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app: learn-hub-app
  ports:
    - protocol: TCP
      name: be-service
      port: 9999
      targetPort: 9999
  type: LoadBalancer
